config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = %w{ www admin}
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end

Rails.application.routes.draw do

  constraints SubdomainConstraint do
    get    'sessions/new'
    
    root                 'routes#show'
    get    'contact'        => 'static_pages#contact'     
    get    'login'          => 'sessions#new'
    post   'login'          => 'sessions#create'
    delete 'logout'         => 'sessions#destroy'
    post   'search'         => 'routes#search'
    post   'cancel'         => 'tickets#cancel_passenger'
    post   'passenger_list' => 'passengers#new'
    

    resources :places, :only => [:new, :create, :index] 
    resources :routes, :only => [:new, :create, :show, :index]
    resources :users
    resources :passengers, :only => [:create] 
    resources :tickets, :only => [:index, :show] 
  end

  resources :accounts
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small> © 2015 FreshBus Travels, All rights reserved
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Freshbus", root_path, id: "logo" %>
    
        <% if logged_in? %>
        <nav>
        <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Booked Tickets", tickets_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path , method: "delete" %>
              </li>
            </ul>
          </li>
          </ul>
        </nav>
        <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>