config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = %w{ www admin}
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end

Rails.application.routes.draw do

  constraints SubdomainConstraint do
    get    'sessions/new'
    
    root                 'routes#show'
    get    'contact'        => 'static_pages#contact'     
    get    'login'          => 'sessions#new'
    post   'login'          => 'sessions#create'
    delete 'logout'         => 'sessions#destroy'
    post   'search'         => 'routes#search'
    post   'cancel'         => 'tickets#cancel_passenger'
    post   'passenger_list' => 'passengers#new'
    

    resources :places, :only => [:new, :create, :index] 
    resources :routes, :only => [:new, :create, :show, :index]
    resources :users
    resources :passengers, :only => [:create] 
    resources :tickets, :only => [:index, :show] 
  end

  resources :accounts
  

end

app/models/account.rb
class Account < ActiveRecord::Base

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :subdomain, presence: true, allow_nil: true

  before_save {self.email = email.downcase }
  
  after_create :create_tenant

  private

	def create_tenant
		Apartment::Tenant.create(subdomain)
	end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:email, :subdomain)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :subdomain %><br>
    <%= f.text_field :subdomain %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Subdomain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.email %></td>
        <td><%= account.subdomain %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @account.email %>
</p>

<p>
  <strong>Subdomain:</strong>
  <%= @account.subdomain %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>